### ISSUE TITLE
Automate installation via BinDeps

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/Yeppp.jl#10]

**Comment by aviks** [comment]
Yes please. Pretty please!

**Comment by panlanfeng** [comment]
I just added a new branch `autobuild` trying to add the dependencies automatically. May not work but I hope someone knows BinDeps better than me will perfect it.

I was not quite sure about how to choose among 

```
armel  armhf  i586  k1om  x86_64
```

Anyone has better knowledge on this?

**Comment by tkelman** [comment]
You can check `Sys.ARCH` - you usually want `x86_64` for most people. If `Sys.ARCH` is `i386` or `i486` or `i586` or `i686` then you should try to use the `i586` Yepp kernels. I have no idea what `k1om` is, and I think Julia on ARM only works on hard-float so far.

**Comment by Maratyszcza** [comment]
k1om is Xeon Phi

**Comment by panlanfeng** [comment]
Let's close this for now. Please file new issue if there is building problem.

**Comment by tkelman** [comment]
Great work! Will test this out at some point. You could consider turning on AppVeyor for Windows testing, see https://github.com/JuliaLang/Example.jl/blob/master/appveyor.yml for the template yml file - just replace `Example` with `Yeppp`
