### ISSUE TITLE
Square-in-place should work, or error

### ISSUE THREAD

**Issue by agbristol** [JuliaLang/Yeppp.jl#16]
``` julia
Yeppp.multiply!(x, x, x) 
```

does not modify x. I think a warning would be appropriate for this. Bonus points if it's possible to make this work!

**Comment by panlanfeng** [comment]
Can you be specific how to reproduce the bug? 
This works fine in my computer.

**Comment by agbristol** [comment]
Sincere apologies. I didn't look at my results carefully enough. Please close the bug.
