### ISSUE TITLE
Yeppp is slower on my machine

### ISSUE THREAD

**Issue by goldfita** [JuliaLang/Yeppp.jl#32]
I'm running the test [here](https://www.reddit.com/r/Julia/comments/5j989q/ways_to_get_around_slow_complex_exponential/) with the result that Yeppp is slower on my machine (Win10 core i7-6820HQ 2.7 GHz, Julia 0.5.0).  My own manual testing is showing the same slow down.  I've looked at the native code to verify different code is called when using Yeppp instead of the normal transcendentals.  My results appear to be even slower than the results in the reddit thread even though I have a faster machine.

Timing map
  0.027443 seconds
Timing loop
  0.014991 seconds
Timing Yeppp
  0.027156 seconds
882255.5526503662 - 482190.3097786134im
882255.5526503662 - 482190.3097786134im
882255.5526503662 - 482190.3097786134im

**Comment by yuyichao** [comment]
I imagine this is dup of https://bitbucket.org/MDukhan/yeppp/issues/49/allow-passing-a-microarchitecture-on-init . It's an issue for Yeppp itself rather than the julia wrapper afaict. These libraries typically needs to update their cpu detection code for new microarchs....

**Comment by goldfita** [comment]
@yuyichao Thanks for letting me know.  Seems like it should just fall back to the next compatible architecture.  This issue can be closed.
